<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LiteNetLib" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mmo.Shared\Mmo.Shared.csproj" />
  </ItemGroup>
</Project>
